version: "3.9"

services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: intelligent-charge-scheduler:latest
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 8081:8081
    volumes:
      - ./credentials.json:/app/credentials.json
      - ics-volume:/app
    restart: always
    command: python3 scheduler.py -i 14

  app:
    depends_on:
      - scheduler
    build:
      context: .
      dockerfile: Dockerfile
    image: intelligent-charge-scheduler:latest
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ics-volume:/app
    restart: always

volumes:
  ics-volume:
